### ISSUE TITLE
doesn't match mention when first thing in a string

### ISSUE THREAD

**Issue by jonschlinkert** [regexps/mentions-regex#2]
given: 

```js
@abc @foo xyz
```
returns

```
[ ' @foo ', 'foo', index: 4, input: '@abc @foo xyz' ]
```

should be `@abc`

**Comment by jonschlinkert** [comment]
I think we should only publish regex libs that have sufficient unit tests.

**Comment by sindresorhus** [comment]
> I think we should only publish regex libs that have sufficient unit tests.

:+1: That includes a lot of tests for false positives.

**Comment by jonschlinkert** [comment]
agreed

**Comment by tunnckoCore** [comment]
> should be @abc

It will, you should control this through options.

**Comment by tunnckoCore** [comment]
As here

```js
str.match(mentionsRegex({flags: 'g', startSpace: false, endSpace: false}))
//=> ['@first', '@tunnckoCore', '@face', '@al', '@here', '@last']
```

**Comment by blakeembrey** [comment]
Sorry, used the github UI incorrectly when opening that the first time :stuck_out_tongue: 

@tunnckoCore That option is broken since it makes it match email domains, etc. I made a PR with an option to fix it.

**Comment by tunnckoCore** [comment]
lol, its flexible. You can control it with different regexp through `opts.match` ;d

Let me add tests, then will discuss? :) And yea, maybe I should fix the default behaviors.
